### ISSUE TITLE
Example projects using clang-tidy-pr-comments

### ISSUE THREAD

**Issue by vkresch** [platisd/clang-tidy-pr-comments#42]
Great project! 
Are there any real life example project on github which are using this github action?
If yes please add them to the readme it would help developers to decide if they want to use it and promote this tool more.
Thanks in advance!

**Comment by platisd** [comment]
You are opening an interesting discussion. 
For a brief period GitHub used to show which repositories use an Action, but they've since removed it and to my knowledge there isn't an automated way to tell who is using the Action. I can only find out by checking the profiles of those that open pull requests or issues, in case they use it in a public repo of theirs.

I know @oleg-derevenetz is using it in a cool project he's involved in.
I am using it in a bunch of projects such as the [Smartcar shield](https://github.com/platisd/smartcar_shield/blob/master/.github/workflows/tests.yml) and [cpp-command-parser](https://github.com/platisd/cpp-command-parser/blob/main/.github/workflows/clang-tidy.yml) from the top of my head.
On of the most interesting use-cases is [Cura](https://github.com/Ultimaker/Cura/blob/main/.github/workflows/printer-linter-pr-post.yml) by Ultimaker, where they parse messages from another tool that happens to use the same syntax as clang-tidy. :exploding_head: 

Some thoughts in regards to publishing a list with projects on README:
The thing is there aren't very creative ways (aside of Cura's example) to use a GitHub Action such as this one. It's mostly copy-pasted configuration and (usually :laughing: ) it just works. So I wouldn't personally find it being used by other projects very "inspiring".
We could start maintaining a list of projects, but it will have to be community driven (i.e. with a hint to "open a PR to add your project to the list") and it may become outdated in case a project stops using the Action but never bothers to update the list. :thinking: 

What do you think?

**Comment by vkresch** [comment]
That's already great. I think it would be interesting to see how people are using the action and it would also help to check the recent PRs of the project to see the clang-tidy comments in "action" :). Listing the libraries which are used in combination might also help. A simple table at the end of the Readme file would be enough:

Project | Workflow
-- | --
[Cura](https://github.com/Ultimaker/Cura/blob/main/.github/workflows/printer-linter-pr-post.yml)| Python + CMake
[Orbit](https://github.com/google/orbit/blob/main/.github/workflows/report-build-and-test.yml) | CMake + Qt
[Smartcar shield](https://github.com/platisd/smartcar_shield/blob/master/.github/workflows/tests.yml) | CMake
[cpp-command-parser](https://github.com/platisd/cpp-command-parser/blob/main/.github/workflows/clang-tidy.yml) | CMake

**Comment by platisd** [comment]
Sure, why not?

Please feel free to open a pull request, otherwise I will look at it after I have finished fixing the bugs introduced by #38 🥲
