### ISSUE TITLE
Add support form many fixes files

### ISSUE THREAD

**Issue by EddyTheCo** [platisd/clang-tidy-pr-comments#78]
I would like to use this action in my projects. 
It is not clear to me if it allows many files or a directory path in the `clang_tidy_fixes` input.

I am using CMake to create the YAML fixes-reports for the project.
CMake  create many report files as explained [here](https://cmake.org/cmake/help/latest/prop_tgt/LANG_CLANG_TIDY_EXPORT_FIXES_DIR.html#prop_tgt:%3CLANG%3E_CLANG_TIDY_EXPORT_FIXES_DIR) .

Enhancing this action to take a directory  or many files as input to create the comments and reviews will be great.
Also if is already possible to input many fixes files to the action, will be nice to make it clearer on the Readme.

**Comment by platisd** [comment]
It's not currently supported and I was not aware of it. Seems like it's a really new feature.
Please feel free to elaborate since it seems like you have already tried t his out:
- What is the point with many files instead of 1? 
- How do these files look like compared to the single-line syntax?

Also please feel free to create a PR which introduces the said feature. :}

**Comment by oleg-derevenetz** [comment]
I would say that generating the `fixes.yml` file (or multiple files of this kind) for the entire project using CMake is not very suitable for this Action because the vast majority of warnings will not apply to lines changed in the corresponding pull request, this is just a waste of time and resources. How to correctly generate the `fixes.yml` for a given Action, taking into account the lines actually changed in the corresponding PR, is already described in the README.
