### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by blozano-tt** [platisd/clang-tidy-pr-comments#82]
When clang-tidy takes issue with system header files, the action tries to look for the system include file in the GITHUB_WORKSPACE?

```
FileNotFoundError: [Errno 2] No such file or directory: '/__w/tt-metal/tt-metal//usr/include/c++/v1/__type_traits/is_copy_constructible.h
```

https://github.com/platisd/clang-tidy-pr-comments/blob/817f9e911bea85d7ea977797dca2862de59905f8/run_action.py#L118

**Comment by oleg-derevenetz** [comment]
Hi @blozano-tt this Action essentially works only with user code from the repository, and it cannot contain system headers. The fact that you get some reports from Clang-Tidy regarding the system headers indicates that you are running the Clang-Tidy incorrectly. You should run it with the line filter that applies only to lines changed in the corresponding pull request (please see the provided examples for details). Naturally, you cannot change the system headers as part of a pull request, don't you?

**Comment by oleg-derevenetz** [comment]
> Here, I pass in only the diff: https://github.com/tenstorrent/tt-metal/blob/a73be8a1bc1c78915b95fc1d7297669fb1ebe72f/.github/workflows/all-static-checks.yaml#L97

Interesting. `clang-tidy-diff` should be able to differentiate user and non-user code, for instance:

https://github.com/ihhub/fheroes2/actions/runs/11353951269/job/31580103981#step:8:10

```
31995 warnings generated.
Suppressed 31[9](https://github.com/ihhub/fheroes2/actions/runs/11353951269/job/31580103981#step:8:10)95 warnings (31992 in non-user code, 3 due to line filter).

Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

In your case, it fails for some reason, I wonder why. In any case, this Action can't process issues with system headers because they are absent in the lines of the pull request, and only the lines changed in the pull request can be commented. There is no way to create comments on an arbitrary file, and even a system header file, which is absent in the repo at all.

**Comment by blozano-tt** [comment]
> Hi @blozano-tt could you please try the #83? This Action, of course, will not start working with system headers, but it will at least ignore them with the appropriate message.

Thanks very much for this PR!

I’ll test tomorrow AM.

**Comment by oleg-derevenetz** [comment]
Hi @blozano-tt Haven't you had time to test the changes in #83 yet?
